# Generated by Django 4.2.4 on 2023-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos_consulta',
            fields=[
                ('CodigoProyecto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('CodiCC', models.CharField(max_length=50)),
                ('NomAux', models.CharField(max_length=50)),
                ('Id_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'PAv_CDOC_Proyectos',
                'managed': False,
            },
        ),
    ]
