# Generated by Django 4.2.4 on 2023-08-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0003_pat_cdo_header_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat_cdo_det_proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProyecto', models.CharField(max_length=10)),
                ('equipo_proyecto', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pat_cdo_header_proyectos',
            name='email_persona',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pat_cdo_header_proyectos',
            name='id_jefe_proyecto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pat_cdo_header_proyectos',
            name='personal_contacto',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pat_cdo_header_proyectos',
            name='CodigoProyecto',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pat_cdo_header_proyectos',
            name='dia_entrega_doc',
            field=models.IntegerField(choices=[(7, '7 días'), (10, '10 días'), (12, '12 días'), (15, '15 días'), (20, '20 días')], default=10),
        ),
    ]
