# Generated by Django 4.2.4 on 2023-08-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0004_pat_cdo_det_proyectos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat_cdoc_listado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProyecto', models.CharField(max_length=10)),
                ('cod_plano_tunning', models.CharField(max_length=30)),
                ('cod_plano_Cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('Ult_rev_plano', models.CharField(blank=True, default='INI', max_length=3, null=True)),
            ],
        ),
    ]
