# Generated by Django 4.2.4 on 2023-08-08 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0006_rename_pat_cdo_det_proyectos_pat_cdoc_det_proyectos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat_cdoc_mov_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProyecto', models.CharField(max_length=10)),
                ('codigo_transmittal', models.CharField(max_length=18)),
                ('cod_plano_tunning', models.CharField(max_length=30)),
                ('cod_plano_Cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('rev_plano', models.CharField(blank=True, max_length=1, null=True)),
                ('tip_documento', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pat_cdoc_listado',
            name='descripcion_plano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pat_cdoc_listado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pat_cdoc_listado',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pat_cdoc_listado',
            name='Ult_rev_plano',
            field=models.CharField(blank=True, default='I', max_length=1, null=True),
        ),
    ]
