# Generated by Django 4.2.4 on 2023-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0007_pat_cdoc_mov_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pat_cdoc_listado',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
