# Generated by Django 4.2.4 on 2023-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0012_alter_pat_cdoc_det_proyectos_equipo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat_cdoc_det_proyectos',
            name='equipo_proyecto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
