# Generated by Django 4.2.4 on 2023-08-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0013_alter_pat_cdoc_det_proyectos_equipo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat_cdoc_det_proyectos',
            name='CodigoProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdocumentos.pat_cdoc_header_proyectos'),
        ),
        migrations.AlterField(
            model_name='pat_cdoc_det_proyectos',
            name='equipo_proyecto',
            field=models.CharField(max_length=36),
        ),
    ]
