# Generated by Django 4.2.4 on 2023-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0016_alter_pat_cdoc_det_proyectos_equipo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat_cdoc_det_proyectos',
            name='CodigoProyecto',
            field=models.CharField(max_length=2000),
        ),
    ]
