# Generated by Django 4.2.4 on 2023-08-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0018_alter_pat_cdoc_det_proyectos_codigoproyecto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listado_personal',
            table='PAV_cdoc_Office365',
        ),
    ]
