# Generated by Django 4.2.4 on 2023-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdocumentos', '0019_alter_listado_personal_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta_proyecto_doc',
            fields=[
                ('CodigoProyecto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
                ('NomAux', models.CharField(max_length=200)),
                ('Total_documento', models.IntegerField()),
                ('transmittal_ing', models.IntegerField()),
                ('transmittal_ot', models.IntegerField()),
            ],
            options={
                'db_table': 'Pav_CDOC_Proyectos_documentos',
                'managed': False,
            },
        ),
    ]
